//Sample data to render on website
const mockRecipes = [
  {
    id: '1',
    name: "Chicken Pasta",
    photo: "https://media.istockphoto.com/id/1057464802/photo/penne-pasta-with-tomato-sauce-chicken-and-cheese-with-ingredients-and-a-place-for-text.jpg?s=612x612&w=0&k=20&c=44bkY4NCsNAY9AT5w9kRl1j_p7Heb7l5QoSAVSJOMDU=",
    ingredientsCount: 8,
    category: 'Lunch',
    cookingTime: 15,
    calorieCount: 720,
    nutrition: {
      protein: '45g',
      carbs: '50g',
      fats: '40g',
      sugar: '2g',
      fiber: '3g',
    },
    ingredients: [
      "225g fettuccine or any pasta of your choice",
      "450g boneless, skinless chicken breasts, cut into bite-sized pieces",
      "Salt",
      "black pepper",
      "2 tablespoons olive oil",
      "3 cloves garlic, minced",
      "240ml heavy cream",
      "100g grated Parmesan cheese",
      "Fresh parsley, chopped (for garnish)",
      "tomato, chopped (for garnish)"
    ],
    procedure: `Cook the pasta according to the package instructions. Drain and set aside.\nSeason chicken pieces with salt and pepper.\nIn a pan, heat olive oil over medium heat.\nAdd chicken and cook until browned and fully cooked. Set aside.\nIn the same pan, add minced garlic and sauté for 1 minute.\nPour in the heavy cream and bring to a gentle simmer.\nStir in Parmesan cheese until melted and the sauce is smooth.\nAdd the cooked chicken to the sauce.\nToss in the cooked pasta until well coated.\nGarnish with chopped parsley.\nEnjoy your quick and tasty Easy Chicken Alfredo Pasta!`,
    recipeTags: ['pasta', 'chicken pasta', 'pasta recipe', 'creamy pasta', 'homemade dinner', 'quick & easy'],
    rating: 4.5,
    numReviews: 25,
    reviews: [
      { id: 1, name: 'John Doe', rating: 5, comment: 'Great recipe!' },
      { id: 2, name: 'Jane Smith', rating: 4, comment: 'Very tasty.' },
    ],
    relatedRecipes: [
      { id: 1, name: 'Italian Pizza', imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&auto=format&fit=crop&q=60' },
      { id: 2, name: 'Chicken Patty Burger', imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=60' },
      { id: 3, name: 'Chilli Noodles', imageUrl: 'https://media.istockphoto.com/id/1292175280/photo/spaghetti-garlic-olive-oil-and-chili-pepper.jpg?s=612x612&w=0&k=20&c=i_4ExsTa5ysw0iwEq_Aq1hI4y9L_69jHpsc5xn1Ht0o=' },
      { id: 4, name: 'Pumpkin Soup', imageUrl: 'https://media.istockphoto.com/id/1045913882/photo/homemade-pumpkin-soup.jpg?s=612x612&w=0&k=20&c=7eV17NtLrSvX53fCm_I5-ZHv5Iv8264AhJKWW6oA8ak=' },
    ],
  },
  {
    id: '2',
    name: 'Chicken Pizza',
    photo: "https://images.unsplash.com/photo-1671106681075-5a7233268cbd?w=600&auto=format&fit=crop&q=60",
    ingredientsCount: 10,
    category: 'Dinner',
    cookingTime: 20,
    calorieCount: 850,
    nutrition: {
      protein: '50g',
      carbs: '60g',
      fats: '35g',
      sugar: '5g',
      fiber: '4g',
    },
    ingredients: [
      "1 pizza base",
      "200g cooked chicken pieces",
      "100g mozzarella cheese",
      "50g tomato sauce",
      "1 teaspoon dried oregano",
      "1 teaspoon chili flakes",
      "2 tablespoons olive oil",
      "1/2 bell pepper, sliced",
      "1/2 onion, sliced",
      "Fresh basil leaves for garnish"
    ],
    procedure: `Preheat oven to 200°C.\nSpread tomato sauce over pizza base.\nSprinkle mozzarella cheese evenly.\nTop with chicken, bell peppers, and onions.\nDrizzle olive oil and sprinkle oregano and chili flakes.\nBake for 15-20 minutes.\nGarnish with fresh basil leaves and serve hot.`,
    recipeTags: ['pizza', 'chicken pizza', 'homemade pizza', 'quick dinner', 'Italian'],
    rating: 4.7,
    numReviews: 30,
    reviews: [
      { id: 1, name: 'John Doe', rating: 5, comment: 'Great recipe!' },
      { id: 2, name: 'Jane Smith', rating: 4, comment: 'Very tasty.' },
    ],
    relatedRecipes: [
      { id: 1, name: 'Italian Pizza', imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&auto=format&fit=crop&q=60' },
      { id: 2, name: 'Chicken Patty Burger', imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=60' },
      { id: 3, name: 'Chilli Noodles', imageUrl: 'https://media.istockphoto.com/id/1292175280/photo/spaghetti-garlic-olive-oil-and-chili-pepper.jpg?s=612x612&w=0&k=20&c=i_4ExsTa5ysw0iwEq_Aq1hI4y9L_69jHpsc5xn1Ht0o=' },
      { id: 4, name: 'Pumpkin Soup', imageUrl: 'https://media.istockphoto.com/id/1045913882/photo/homemade-pumpkin-soup.jpg?s=612x612&w=0&k=20&c=7eV17NtLrSvX53fCm_I5-ZHv5Iv8264AhJKWW6oA8ak=' },
    ],
  },
  {
    id: '3',
    name: 'Tomato Basil Soup',
    photo: "https://media.istockphoto.com/id/1487559996/photo/gazpacho-soup-traditional-spanish-cold-tomato-soup-of-fresh-raw-vegetables.jpg?s=612x612&w=0&k=20&c=-K784ldVfERI-NApfiLCGOXYp9QtLbSHOb6RdnYfMRA=",
    ingredientsCount: 6,
    category: 'Breakfast',
    cookingTime: 25,
    calorieCount: 250,
    nutrition: {
      protein: '5g',
      carbs: '30g',
      fats: '10g',
      sugar: '8g',
      fiber: '6g',
    },
    ingredients: [
      "500g fresh tomatoes",
      "1 onion, chopped",
      "3 cloves garlic, minced",
      "2 tablespoons olive oil",
      "500ml vegetable broth",
      "Fresh basil leaves for garnish"
    ],
    procedure: `Heat olive oil in a pot.\nSauté onions and garlic until soft.\nAdd chopped tomatoes and cook for 10 minutes.\nPour in vegetable broth and simmer for 15 minutes.\nBlend until smooth.\nGarnish with fresh basil and serve warm.`,
    recipeTags: ['soup', 'tomato soup', 'healthy', 'vegetarian', 'light meal'],
    rating: 4.6,
    numReviews: 22,
    reviews: [
      { id: 1, name: 'John Doe', rating: 5, comment: 'Great recipe!' },
      { id: 2, name: 'Jane Smith', rating: 4, comment: 'Very tasty.' },
    ],
    relatedRecipes: [
      { id: 1, name: 'Italian Pizza', imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&auto=format&fit=crop&q=60' },
      { id: 2, name: 'Chicken Patty Burger', imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=60' },
      { id: 3, name: 'Chilli Noodles', imageUrl: 'https://media.istockphoto.com/id/1292175280/photo/spaghetti-garlic-olive-oil-and-chili-pepper.jpg?s=612x612&w=0&k=20&c=i_4ExsTa5ysw0iwEq_Aq1hI4y9L_69jHpsc5xn1Ht0o=' },
      { id: 4, name: 'Pumpkin Soup', imageUrl: 'https://media.istockphoto.com/id/1045913882/photo/homemade-pumpkin-soup.jpg?s=612x612&w=0&k=20&c=7eV17NtLrSvX53fCm_I5-ZHv5Iv8264AhJKWW6oA8ak=' },
    ],
  },
  {
    id: '4',
    name: 'Paneer Butter Masala',
    photo: "https://media.istockphoto.com/id/524996497/photo/paneer-masala.jpg?s=612x612&w=0&k=20&c=16zYuXomRvBJbuCFjEhxHgIYdP91YtqPRPqO5PqiAE4=",
    ingredientsCount: 10,
    category: 'Lunch',
    cookingTime: 30,
    calorieCount: 450,
    nutrition: {
      protein: '18g',
      carbs: '35g',
      fats: '28g',
      sugar: '6g',
      fiber: '4g',
    },
    ingredients: [
      "250g paneer (cottage cheese), cubed",
      "2 tablespoons butter",
      "1 large onion, finely chopped",
      "2 tomatoes, pureed",
      "2 tablespoons cashew paste",
      "1 teaspoon ginger-garlic paste",
      "1/2 teaspoon turmeric powder",
      "1 teaspoon red chili powder",
      "1 teaspoon garam masala",
      "Salt to taste",
      "1/2 cup heavy cream",
      "1 teaspoon dried fenugreek leaves (kasuri methi)",
      "Fresh coriander for garnish"
    ],
    procedure: `Heat butter in a pan over medium heat.\nAdd onions and sauté until golden brown.\nStir in ginger-garlic paste and cook for a minute.\nAdd tomato puree and cook until oil separates.\nMix in cashew paste and cook for another 2 minutes.\nAdd turmeric, red chili powder, garam masala, and salt. Stir well.\nAdd paneer cubes and mix gently.\nPour in the heavy cream and dried fenugreek leaves.\nCook for 5 minutes on low heat.\nGarnish with fresh coriander.\nServe hot with naan or rice!`,
    recipeTags: ['paneer', 'vegetarian', 'indian food', 'curry', 'creamy paneer', 'restaurant style'],
    rating: 4.7,
    numReviews: 30,
    reviews: [
      {
        id: 1,
        name: 'Amit Kumar',
        rating: 5,
        comment: 'Tastes just like restaurant-style!',
      },
      {
        id: 2,
        name: 'Priya Sharma',
        rating: 4,
        comment: 'Really creamy and flavorful.',
      },
    ],
    relatedRecipes: [
      { id: 1, name: 'Butter Chicken', imageUrl: 'https://media.istockphoto.com/id/618457124/photo/butter-chicken-served-with-homemade-indian-naan-bread.jpg?s=612x612&w=0&k=20&c=7FoiHoDtocfPvQIaRFfFani4e5lkfMTNl_619rTTh4g=' },
      { id: 2, name: 'Dal Makhani', imageUrl: 'https://media.istockphoto.com/id/1440057519/photo/daal-makhani-butter-with-white-rice-served-in-dish-isolated-on-table-side-view-of-middle-east.jpg?s=612x612&w=0&k=20&c=yVu4UgkGSZYkXsBgFntB6aVvL27nNkzEaQKCFYFEXTI=' },
    ],
  },
  //Adding other recipes
];

export default mockRecipes;
